import React from 'react';
import styled, {css} from 'styled-components';
import {Grid, Row, Col} from 'react-styled-flexboxgrid';
import Truncate from 'react-truncate';
import Button from '../Button'
import {rem} from 'polished';

export const SectionLink = styled.div`
  text-align: center;
  
  >button, >a {
    width: 100%;
    max-width: 340px;
    font-size: ${rem('16px')};
  }
`;

export const Section = styled.div`
  padding-top: ${rem('60px')};
  padding-bottom: ${rem('90px')};
  overfloe: hidden;
`;

export const News = styled.div`
  margin-bottom: ${rem('50px')};

  > ${Row} {
    margin-left: 0;
    margin-right: 0;
    
    > ${Col} {
      padding-left: 0;
      padding-right: 0;
    }
  }
 
`;

export const Wrapper = styled.div`
  > ${Row} {
    margin-left: ${rem('-25px')};
    margin-right: ${rem('-25px')};
    
    > ${Col} {
      padding-left: ${rem('25px')};
      padding-right: ${rem('25px')}
    }
  }
 
  h3 {
    margin-bottom: ${rem('38px')};
    color: ${p => p.theme.colors.black};
  }
`;

export const Item = styled.div`
  margin-bottom: ${rem('50px')};
`;

export const Image = styled.div`
  height: 294px;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  margin-bottom: ${rem('22px')};
  
  a {
    display: block;
    width: 100%;
    height: 100%;
  }
`;

export const Title = styled.h4`
  line-height: normal;
  margin-bottom: ${rem('22px')};
  color: ${p => p.theme.colors.black};
  
  a {
    color: inherit;
  }
`;

export const Desc = styled.div`
  font-size: ${rem('14px')};
  font-weight: normal;
  line-height: 1.36;
  color: ${p => p.theme.colors.dark};
  margin-bottom: ${rem('28px')};
`;

export const Content = styled.div`
  overflow: hidden;
  padding-right: ${rem('20px')};
`;

export const ReadMore = styled.div`
  a {
    color: ${p => p.theme.colors.primary};
    letter-spacing: -0.2px;
  }
`;

export const Logo = styled.div`
  font-size: 0;
  line-height: 0;
  margin-bottom: ${rem('25px')};
`;

export default () => (
  <Section>
    <Wrapper as={Grid}>
      <Row>
        <Col md={3}>
          <Logo>
            <img src="/static/images/scbc-logo.svg" alt="scbc" width="152px"/>
          </Logo>
          <h3>Financial news generated by the community for the community.</h3>
          <p className="text-grey">Contribute to the future of finance. Here we invite open discussion for everyone that is interested in what the next generation of finance holds and how we can get there.</p>
        </Col>
        <Col md={9}>
          <News>
            <Row>
              <Col sm={4}>
                <Item>
                  <Image style={{backgroundImage: 'url(http://placekitten.com/300/294)'}}><a href="#"/></Image>
                  <Content>
                    <Title>
                      <a href="#">Etherium - rise and fall, and rise again</a>
                    </Title>
                    <Desc>
                      <Truncate lines={2}>Use your credit card or swift to get your first bircoing, ether or other cryptios.</Truncate>
                    </Desc>
                    <ReadMore>
                      <a href="">Continue reading</a>
                    </ReadMore>
                  </Content>
                </Item>
              </Col>
              <Col sm={4}>
                <Item>
                  <Image style={{backgroundImage: 'url(http://placekitten.com/300/294)'}}><a href="#"/></Image>
                  <Content>
                    <Title>
                      <a href="#">Single line title</a>
                    </Title>
                    <Desc>
                      <Truncate lines={2}>Use your credit card or swift to get your first bircoing, ether or other cryptios.</Truncate>
                    </Desc>
                    <ReadMore>
                      <a href="">Continue reading</a>
                    </ReadMore>
                  </Content>
                </Item>
              </Col>
              <Col sm={4}>
                <Item>
                  <Image style={{backgroundImage: 'url(http://placekitten.com/300/294)'}}><a href="#"/></Image>
                  <Content>
                    <Title>
                      <a href="#">Etherium - rise and fall, and rise again</a>
                    </Title>
                    <Desc>
                      <Truncate lines={2}>Use your credit card or swift to get your first bircoing, ether or other cryptios. Use your credit card or swift to get your first bircoing, ether or other cryptios.</Truncate>
                    </Desc>
                    <ReadMore>
                      <a href="">Continue reading</a>
                    </ReadMore>
                  </Content>
                </Item>
              </Col>
            </Row>
          </News>
        </Col>
      </Row>

      <SectionLink>
        <h4>Share. Discuss. Connect.</h4>
        <Button bordered href="#">Join our 90,000 members community</Button>
      </SectionLink>
    </Wrapper>
  </Section>
);